language: node_js
node_js: stable

cache:
  directories:
    - node_modules

install:
  - yarn

script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  on:
    branch: source
  local-dir: dist

branches:
  only:
    - source
